### ISSUE TITLE
pkg_resources:DistributionNotFound: Pokedex==0.1

### ISSUE THREAD

**Issue by immewnity** [veekun/pokedex#142]
I'm trying to set up the Pokedex database on my server using SQL, but I'm getting this error.

/veekundata/pokedex/bin# python pokedex load -e mysql://                                     myusername:mypassword@localhost/data_veekunpokedex
Traceback (most recent call last):
  File "pokedex", line 5, in <module>
    from pkg_resources import load_entry_point
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 3020, in <                                     module>
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 614, in _b                                     uild_master
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 920, in re                                     quire
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 807, in re                                     solve
pkg_resources.DistributionNotFound: Pokedex==0.1

Any ideas?

**Comment by magical** [comment]
Hi. Did you ever figure this out?

**Comment by magical** [comment]
Closing as the reporter has likely either solved their problem or given up by now.

@immewnity If you still need help setting up the pokedex, please leave another comment here or [join us on irc](http://veekun.com/chat).
