### ISSUE TITLE
pokedex reindex fails with sqlalchemy.exc.InvalidRequestError:

### ISSUE THREAD

**Issue by ciencia** [veekun/pokedex#143]
```
Connected to database sqlite:////home/jesus/git/veekun/pokedex/pokedex/data/pokedex.sqlite (from default)
Opened lookup index /home/jesus/git/veekun/pokedex/pokedex/data/whoosh-index (from default)
Traceback (most recent call last):
  File "bin/pokedex", line 9, in <module>
    load_entry_point('Pokedex==0.1', 'console_scripts', 'pokedex')()
  File "/home/jesus/git/veekun/pokedex/pokedex/main.py", line 32, in setuptools_entry
    main(*sys.argv)
  File "/home/jesus/git/veekun/pokedex/pokedex/main.py", line 27, in main
    func(*args)
  File "/home/jesus/git/veekun/pokedex/pokedex/main.py", line 174, in command_reindex
    lookup = get_lookup(options, session=session, recreate=True)
  File "/home/jesus/git/veekun/pokedex/pokedex/main.py", line 87, in get_lookup
    lookup.rebuild_index()
  File "/home/jesus/git/veekun/pokedex/pokedex/lookup.py", line 198, in rebuild_index
    for row in q.yield_per(5):
  File "/home/jesus/git/veekun/pokedex/pokedex/db/multilang.py", line 216, in __iter__
    return super(MultilangQuery, self).__iter__()
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/query.py", line 2505, in __iter__
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/query.py", line 2945, in _compile_context
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/query.py", line 3314, in setup_context
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/loading.py", line 253, in _setup_entity_query
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/interfaces.py", line 505, in setup
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/strategies.py", line 1145, in setup_query
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/loading.py", line 253, in _setup_entity_query
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/interfaces.py", line 505, in setup
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/strategies.py", line 1097, in setup_query
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/query.py", line 596, in _no_yield_per
sqlalchemy.exc.InvalidRequestError: The yield_per Query option is currently not compatible with joined collection eager loading.  Please specify lazyload('*') or query.enable_eagerloads(False) in order to proceed with query.yield_per().
```

I've fixed it myself with this change, [as suggested by the docs](http://docs.sqlalchemy.org/en/latest/orm/query.html#sqlalchemy.orm.query.Query.yield_per):

```
diff --git a/pokedex/lookup.py b/pokedex/lookup.py
index d8143b1..1234d92 100644
--- a/pokedex/lookup.py
+++ b/pokedex/lookup.py
@@ -195,7 +195,7 @@ class PokedexLookup(object):
         for cls in self.indexed_tables.values():
             q = self.session.query(cls).order_by(cls.id)
 
-            for row in q.yield_per(5):
+            for row in q.yield_per(5).enable_eagerloads(False):
                 row_key = dict(table=unicode(cls.__tablename__),
                                row_id=unicode(row.id))
```

**Comment by magical** [comment]
Maybe just drop `yield_per`. The tables in question aren't *that* large.
