### ISSUE TITLE
Empty pokedex.sqlite

### ISSUE THREAD

**Issue by bonzairob** [veekun/pokedex#169]
Hi, I've just done a clean install via `python setup.py` and the pokedex.sqlite file in `/usr/local/lib/python2.7/site-packages/Pokedex-0.1-py2.7.egg/pokedex/data` is zero bytes. Everything errors the same, CLI and python module:

```
$ pokedex lookup "Charizard"
Connected to database sqlite:////usr/local/lib/python2.7/site-packages/Pokedex-0.1-py2.7.egg/pokedex/data/pokedex.sqlite (from default)
Opened lookup index /usr/local/lib/python2.7/site-packages/Pokedex-0.1-py2.7.egg/pokedex/data/whoosh-index (from default)
Traceback (most recent call last):
  File "/usr/local/bin/pokedex", line 9, in <module>
    load_entry_point('Pokedex==0.1', 'console_scripts', 'pokedex')()
  File "/usr/local/lib/python2.7/site-packages/Pokedex-0.1-py2.7.egg/pokedex/main.py", line 27, in setuptools_entry
    main(*sys.argv)
  File "/usr/local/lib/python2.7/site-packages/Pokedex-0.1-py2.7.egg/pokedex/main.py", line 23, in main
    args.func(parser, args)
  File "/usr/local/lib/python2.7/site-packages/Pokedex-0.1-py2.7.egg/pokedex/main.py", line 318, in command_lookup
    results = lookup.lookup(name)
  File "/usr/local/lib/python2.7/site-packages/Pokedex-0.1-py2.7.egg/pokedex/lookup.py", line 488, in lookup
    locale = self._get_current_locale()
  File "/usr/local/lib/python2.7/site-packages/Pokedex-0.1-py2.7.egg/pokedex/lookup.py", line 396, in _get_current_locale
    self.session.default_language_id)
  File "build/bdist.macosx-10.6-x86_64/egg/sqlalchemy/orm/query.py", line 831, in get
  File "build/bdist.macosx-10.6-x86_64/egg/sqlalchemy/orm/query.py", line 864, in _get_impl
  File "build/bdist.macosx-10.6-x86_64/egg/sqlalchemy/orm/loading.py", line 219, in load_on_ident
  File "build/bdist.macosx-10.6-x86_64/egg/sqlalchemy/orm/query.py", line 2693, in one
  File "/usr/local/lib/python2.7/site-packages/Pokedex-0.1-py2.7.egg/pokedex/db/multilang.py", line 216, in __iter__
    return super(MultilangQuery, self).__iter__()
  File "build/bdist.macosx-10.6-x86_64/egg/sqlalchemy/orm/query.py", line 2736, in __iter__
  File "build/bdist.macosx-10.6-x86_64/egg/sqlalchemy/orm/query.py", line 2751, in _execute_and_instances
  File "build/bdist.macosx-10.6-x86_64/egg/sqlalchemy/engine/base.py", line 914, in execute
  File "build/bdist.macosx-10.6-x86_64/egg/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
  File "build/bdist.macosx-10.6-x86_64/egg/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
  File "build/bdist.macosx-10.6-x86_64/egg/sqlalchemy/engine/base.py", line 1146, in _execute_context
  File "build/bdist.macosx-10.6-x86_64/egg/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
  File "build/bdist.macosx-10.6-x86_64/egg/sqlalchemy/util/compat.py", line 200, in raise_from_cause
  File "build/bdist.macosx-10.6-x86_64/egg/sqlalchemy/engine/base.py", line 1139, in _execute_context
  File "build/bdist.macosx-10.6-x86_64/egg/sqlalchemy/engine/default.py", line 450, in do_execute
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: languages [SQL: u'SELECT languages.id AS languages_id, languages.iso639 AS languages_iso639, languages.iso3166 AS languages_iso3166, languages.identifier AS languages_identifier, languages.official AS languages_official, languages."order" AS languages_order \nFROM languages \nWHERE languages.id = ?'] [parameters: (9,)]
```
Kind of looks like the sqlite file was never made out of the CSVs, maybe?

OS X 10.11.3, Python 2.7. No errors on install. Could do with a little "How to use" in the readme though!

**Comment by magical** [comment]
`setup.py` doesn't create the db, it just installs the `pokedex` command. You have to run `pokedex setup` or `pokedex load` to actually create the db.

**Comment by bonzairob** [comment]
Yep, that's got it, thanks. I could definitely do with a quick walkthrough though. For instance, how can I get a species's base stats via the lookup module as a python module?

**Comment by codemonkey85** [comment]
@bonzairob Probably not the **best** example, but you can see how I use SQLite to query the DB in C++ here: https://github.com/codemonkey85/PKMDS/blob/master/lib/pkmds_sql.cpp

**Comment by magical** [comment]
Sounds like this got resolved? Closing.
